### ISSUE TITLE
Is there any way I can use this is iOS?

### ISSUE THREAD

**Issue by iblessedi** [Hunter-Dolan/Crypt#3]
Hello! I need to be able to encrypt string in php and then decryot it in iOS, using swift. Is there any libraries for swift I can use with this one? Thank you.

**Comment by Hunter-Dolan** [comment]
Hi, this library is pretty old and isn't maintained any longer. In addition the method it used to encrypt cannot compare to modern standards.

I would recommend looking for a php/swift library that is capable of using the AES encryption standard. As long as each lib follows the standard, they will be interoperable.

That said, if you are just trying to create a secure and encrypted connection between an app and a server, don't reinvent the wheel and look no further than HTTPS. HTTPS will use AES encryption, and RSA handshake, and will protect against man in the middle attacks.

You can setup https for free on any server by using cloudflare, or by buying a certificate from an issuer.

Hope this helps!

Cheers,

-Hunter
